### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by Gustl22** [nileshk/wp-fullcalendar#1]
Hi Nilesh,

would it bother you, to release a working alpha version?
Official version becomes more and more obsolete.

Thanks :)

~_BTW: Currently I get the error: TypeError: themeClass is not a constructor in fullcalendar.js:10829:25_~
Solved it by adding parameter to [inline.js](https://github.com/nileshk/wp-fullcalendar/blob/master/includes/js/inline.js)
```
var fullcalendar_args = {
        themeSystem: 'default'
        ...
}
```

**Comment by Gustl22** [comment]
I made some [adjustments](https://github.com/Gustl22/wp-fullcalendar) (more options for admin) and updated to fullcalendar 3.10.0 (with bootstrap support). If you're interested i can make some PRs.

**Comment by Gustl22** [comment]
I started a fresh repository in my [dev account](https://github.com/Oberhauser-Dev/gb-fullcalendar).

It's called **GB FullCalendar** and uses the newest version of **FullCalendar v5.1** and is built as a Gutenberg Block (with React) and remains usable with shortcodes. Further the category filter options were slightly improved. Still in alpha state, but I would be happy to review Merge-Requests for missing / new features :grin: 

Checkout the [pre-release](https://github.com/Oberhauser-Dev/gb-fullcalendar/releases/tag/v0.1.0-alpha.0) for testing etc.

**Comment by nileshk** [comment]
That looks great.  I'm no longer using wp-fullcalendar, so haven't been
maintaining my fork, but it's nice to see the work you've done.
